name: qmake CI

on: [push]



jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: jurplel/install-qt-action@v2.2.1
    - uses: actions/checkout@v1
    - name: qmake
      run: qmake entity-block.pro
    - name: make
      run: make
    - name: make check
      run: make check
